"""initial: pipeline + inventory + alerts + reorder_rules

Revision ID: 16b789708acc
Revises: 
Create Date: 2026-02-14 21:28:29.615325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b789708acc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_public_id'), 'alerts', ['public_id'], unique=True)
    op.create_index(op.f('ix_alerts_sku'), 'alerts', ['sku'], unique=False)
    op.create_index(op.f('ix_alerts_store_id'), 'alerts', ['store_id'], unique=False)
    op.create_index('ix_alerts_store_resolved', 'alerts', ['store_id', 'resolved'], unique=False)
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=16), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('retail_price', sa.Float(), nullable=False),
    sa.Column('predicted_demand_30d', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('safety_stock', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('last_sold_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_items_public_id'), 'inventory_items', ['public_id'], unique=True)
    op.create_index(op.f('ix_inventory_items_sku'), 'inventory_items', ['sku'], unique=True)
    op.create_index('ix_inventory_items_status', 'inventory_items', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_items_store_id'), 'inventory_items', ['store_id'], unique=False)
    op.create_index('ix_inventory_items_store_sku', 'inventory_items', ['store_id', 'sku'], unique=False)
    op.create_table('normalized_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=128), nullable=False),
    sa.Column('category_id', sa.String(length=128), nullable=True),
    sa.Column('series_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('is_interpolated', sa.Boolean(), nullable=False),
    sa.Column('is_outlier_adjusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_series_category_id'), 'normalized_series', ['category_id'], unique=False)
    op.create_index(op.f('ix_normalized_series_series_date'), 'normalized_series', ['series_date'], unique=False)
    op.create_index(op.f('ix_normalized_series_sku_id'), 'normalized_series', ['sku_id'], unique=False)
    op.create_index('ix_normalized_series_store_date', 'normalized_series', ['store_id', 'series_date'], unique=False)
    op.create_index(op.f('ix_normalized_series_store_id'), 'normalized_series', ['store_id'], unique=False)
    op.create_index('ix_normalized_series_store_sku_date', 'normalized_series', ['store_id', 'sku_id', 'series_date'], unique=True)
    op.create_table('pipeline_store_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_store_config_store_id'), 'pipeline_store_config', ['store_id'], unique=True)
    op.create_table('raw_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('external_line_id', sa.String(length=128), nullable=True),
    sa.Column('sku_raw', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=True),
    sa.Column('variant_id', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_date_utc', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_orders_external_order_id'), 'raw_orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_raw_orders_order_date_utc'), 'raw_orders', ['order_date_utc'], unique=False)
    op.create_index(op.f('ix_raw_orders_sku_raw'), 'raw_orders', ['sku_raw'], unique=False)
    op.create_index('ix_raw_orders_store_date', 'raw_orders', ['store_id', 'order_date_utc'], unique=False)
    op.create_index(op.f('ix_raw_orders_store_id'), 'raw_orders', ['store_id'], unique=False)
    op.create_table('raw_products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('sku_raw', sa.String(length=128), nullable=False),
    sa.Column('product_id', sa.String(length=128), nullable=True),
    sa.Column('variant_id', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_products_sku_raw'), 'raw_products', ['sku_raw'], unique=False)
    op.create_index(op.f('ix_raw_products_store_id'), 'raw_products', ['store_id'], unique=False)
    op.create_index('ix_raw_products_store_sku', 'raw_products', ['store_id', 'sku_raw'], unique=True)
    op.create_table('raw_refunds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refund_date_utc', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_refunds_external_order_id'), 'raw_refunds', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_raw_refunds_refund_date_utc'), 'raw_refunds', ['refund_date_utc'], unique=False)
    op.create_index(op.f('ix_raw_refunds_store_id'), 'raw_refunds', ['store_id'], unique=False)
    op.create_table('reorder_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=False),
    sa.Column('reorder_qty', sa.Integer(), nullable=False),
    sa.Column('auto_reorder', sa.Boolean(), nullable=False),
    sa.Column('supplier_email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reorder_rules_sku'), 'reorder_rules', ['sku'], unique=False)
    op.create_index(op.f('ix_reorder_rules_store_id'), 'reorder_rules', ['store_id'], unique=False)
    op.create_index('ix_reorder_rules_store_sku', 'reorder_rules', ['store_id', 'sku'], unique=True)
    op.create_table('sku_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_id', sa.String(length=64), nullable=False),
    sa.Column('sku_raw', sa.String(length=128), nullable=False),
    sa.Column('canonical_sku', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sku_mappings_canonical_sku'), 'sku_mappings', ['canonical_sku'], unique=False)
    op.create_index(op.f('ix_sku_mappings_sku_raw'), 'sku_mappings', ['sku_raw'], unique=False)
    op.create_index(op.f('ix_sku_mappings_store_id'), 'sku_mappings', ['store_id'], unique=False)
    op.create_index('ix_sku_mappings_store_raw', 'sku_mappings', ['store_id', 'sku_raw'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sku_mappings_store_raw', table_name='sku_mappings')
    op.drop_index(op.f('ix_sku_mappings_store_id'), table_name='sku_mappings')
    op.drop_index(op.f('ix_sku_mappings_sku_raw'), table_name='sku_mappings')
    op.drop_index(op.f('ix_sku_mappings_canonical_sku'), table_name='sku_mappings')
    op.drop_table('sku_mappings')
    op.drop_index('ix_reorder_rules_store_sku', table_name='reorder_rules')
    op.drop_index(op.f('ix_reorder_rules_store_id'), table_name='reorder_rules')
    op.drop_index(op.f('ix_reorder_rules_sku'), table_name='reorder_rules')
    op.drop_table('reorder_rules')
    op.drop_index(op.f('ix_raw_refunds_store_id'), table_name='raw_refunds')
    op.drop_index(op.f('ix_raw_refunds_refund_date_utc'), table_name='raw_refunds')
    op.drop_index(op.f('ix_raw_refunds_external_order_id'), table_name='raw_refunds')
    op.drop_table('raw_refunds')
    op.drop_index('ix_raw_products_store_sku', table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_store_id'), table_name='raw_products')
    op.drop_index(op.f('ix_raw_products_sku_raw'), table_name='raw_products')
    op.drop_table('raw_products')
    op.drop_index(op.f('ix_raw_orders_store_id'), table_name='raw_orders')
    op.drop_index('ix_raw_orders_store_date', table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_sku_raw'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_order_date_utc'), table_name='raw_orders')
    op.drop_index(op.f('ix_raw_orders_external_order_id'), table_name='raw_orders')
    op.drop_table('raw_orders')
    op.drop_index(op.f('ix_pipeline_store_config_store_id'), table_name='pipeline_store_config')
    op.drop_table('pipeline_store_config')
    op.drop_index('ix_normalized_series_store_sku_date', table_name='normalized_series')
    op.drop_index(op.f('ix_normalized_series_store_id'), table_name='normalized_series')
    op.drop_index('ix_normalized_series_store_date', table_name='normalized_series')
    op.drop_index(op.f('ix_normalized_series_sku_id'), table_name='normalized_series')
    op.drop_index(op.f('ix_normalized_series_series_date'), table_name='normalized_series')
    op.drop_index(op.f('ix_normalized_series_category_id'), table_name='normalized_series')
    op.drop_table('normalized_series')
    op.drop_index('ix_inventory_items_store_sku', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_store_id'), table_name='inventory_items')
    op.drop_index('ix_inventory_items_status', table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_sku'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_public_id'), table_name='inventory_items')
    op.drop_table('inventory_items')
    op.drop_index('ix_alerts_store_resolved', table_name='alerts')
    op.drop_index(op.f('ix_alerts_store_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_sku'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_public_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
